// app/layout.tsx

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { CartProvider } from "@/context/CartContext";
import { WishlistProvider } from "@/context/WishlistContext";

import CartModalContainer from "@/components/cart/CartModalContainer";
import WishlistModalContainer from "@/components/wishlist/WishlistModalContainer";
// Optionally: import Header, Footer, ToastProvider, etc.

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "TrendMark",
  description: "Generated by Umutesi Kelia",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-gray-900`}
      >
        <CartProvider>
          <WishlistProvider>
            {/* Global Modals */}
            <CartModalContainer />
            <WishlistModalContainer />

            {/* Optional: <Header /> */}

            {children}

            {/* Optional: <Footer /> */}
          </WishlistProvider>
        </CartProvider>
      </body>
    </html>
  );
}
