"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { CartProvider } from "@/context/CartContext";
import { WishlistProvider } from "@/context/WishlistContext";
import { DarkModeProvider } from '@/context/DarkModeContext';

import CartModalContainer from "@/components/cart/CartModalContainer";
import WishlistModalContainer from "@/components/wishlist/WishlistModalContainer";
// Optionally: import Header, Footer, ToastProvider, etc.

import { useEffect } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

// export const metadata: Metadata = {
//   title: "TrendMark",
//   description: "Generated by Umutesi Kelia",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  useEffect(() => {
    if (
      typeof window !== "undefined" &&
      !(window as unknown as { tidioChatApi?: unknown }).tidioChatApi
    ) {
      const script = document.createElement("script");
      script.src = "//code.tidio.co/0qnyepnhu3ku4frnjx7ubn1l957lyhvs.js";
      script.async = true;
      document.body.appendChild(script);
    }
  }, []);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-gray-900 dark:bg-black dark:text-white`}
      >
        <DarkModeProvider>
          <CartProvider>
            <WishlistProvider>
              {/* Global Modals */}
              <CartModalContainer />
              <WishlistModalContainer />

              {/* Optional: <Header /> */}

              {children}

              {/* Optional: <Footer /> */}
            </WishlistProvider>
          </CartProvider>
        </DarkModeProvider>
      </body>
    </html>
  );
}
